# Generated by Django 4.2.29 on 2026-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacedoc',
            name='type',
            field=models.CharField(choices=[('todo', 'To-Do List'), ('project', 'Project Tracker'), ('goal', 'Goal Tracker'), ('note', 'Notes'), ('habit', 'Habit Tracker')], max_length=20),
        ),
    ]
